name: weather_share
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1 
  auto_route: ^8.1.3 
  provider: ^6.1.2
  get_it: ^7.7.0 
  material_symbols_icons: ^4.2741.0
  image_picker: ^1.1.1
  intl: ^0.19.0
  image_cropper: ^6.0.0 
  path_provider: ^2.1.3 
  styled_text: ^8.1.0
  path: any
  url_launcher: ^6.2.6
  cached_network_image: ^3.3.1 

  #Firebase
  firebase_auth: ^4.19.5 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  custom_lint: ^0.6.4

flutter: 
  uses-material-design: true
  assets:
    - image/
    - image/2.0x/
    - image/3.0x/

  
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
